"""add athlete location and notes

Revision ID: 81ce85ba2f6b
Revises: 9d344e3605ed
Create Date: 2026-10-06 01:02:38.068352

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81ce85ba2f6b"
down_revision: str | Sequence[str] | None = "9d344e3605ed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("location", sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column("notes", sa.String(length=2000), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("athletes", schema=None) as batch_op:
        batch_op.drop_column("notes")
        batch_op.drop_column("location")

    # ### end Alembic commands ###
