"""create athletes table

Revision ID: 9d344e3605ed
Revises:
Create Date: 2026-10-06 01:02:29.607406

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d344e3605ed"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "athletes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=80), nullable=False),
        sa.Column("last_name", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("graduation_year", sa.Integer(), nullable=False),
        sa.Column("primary_position", sa.String(length=8), nullable=False),
        sa.Column("club_team", sa.String(length=120), nullable=False),
        sa.Column("gpa", sa.Float(), nullable=True),
        sa.Column("highlight_reel_url", sa.String(length=500), nullable=True),
        sa.Column(
            "status", sa.String(length=32), server_default="unreviewed", nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("athletes")
    # ### end Alembic commands ###
