[project]
name = "toprostr-api"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.142.2",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pyright>=1.1.414",
    "pytest>=9.1.1",
    "ruff>=0.16.10",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
